use crate::decay::DecayScore;
use crate::matcher::Recommendation;
use anyhow::Result;
use printpdf::*;
use std::collections::HashSet;
use std::path::Path;

const PAGE_W: f64 = 210.0;
const PAGE_H: f64 = 297.0;
const LEFT: f64 = 20.0;
const START_Y: f64 = 275.0;
const BOTTOM_MARGIN: f64 = 22.0;

fn new_page(doc: &PdfDocumentReference, n: &mut u32) -> (PdfLayerReference, f64) {
    *n += 1;
    let (pi, li) = doc.add_page(Mm(PAGE_W), Mm(PAGE_H), &format!("Layer {}", n));
    (doc.get_page(pi).get_layer(li), START_Y)
}

// ─── Markdown ────────────────────────────────────────────────────────────────

pub fn export_markdown(
    path: &Path,
    match_id: &str,
    team: &str,
    minute: u32,
    timestamp: &str,
    scores: &[DecayScore],
    subbed_off: &HashSet<String>,
    recommendation: Option<&Recommendation>,
) -> Result<()> {
    let mut lines: Vec<String> = Vec::new();

    lines.push("# SUBS Analysis Report".into());
    lines.push(String::new());
    lines.push(format!("**Match ID:** {}  ", match_id));
    lines.push(format!("**Team:** {}  ", team));
    lines.push(format!("**Minute Analysed:** {}  ", minute));
    lines.push(format!("**Generated:** {}  ", timestamp));
    lines.push(String::new());
    lines.push("---".into());
    lines.push(String::new());

    // Decay table
    lines.push("## Decay Table".into());
    lines.push(String::new());
    lines.push("| Player | Pos | Baseline APM | Recent APM | Decay |".into());
    lines.push("|:-------|:----|------------:|----------:|------:|".into());

    let mut any_subbed = false;
    for s in scores {
        let is_sub = subbed_off.contains(&s.player_name);
        if is_sub {
            any_subbed = true;
        }
        let name = if is_sub {
            format!("{} \\*", s.player_name)
        } else {
            s.player_name.clone()
        };
        lines.push(format!(
            "| {} | {} | {:.2} | {:.2} | {:.2} |",
            name, s.position, s.baseline_apm, s.recent_apm, s.score
        ));
    }

    if any_subbed {
        lines.push(String::new());
        lines.push("> \\* = already substituted off".into());
    }

    lines.push(String::new());
    lines.push("---".into());
    lines.push(String::new());

    // Recommendation
    match recommendation {
        None => {
            lines.push(format!(
                "## No Substitution Recommended -- Minute {}",
                minute
            ));
            lines.push(String::new());
            lines.push("All players are performing at or near baseline levels.".into());
        }
        Some(rec) => {
            lines.push(format!(
                "## Substitution Recommendation -- Minute {}",
                minute
            ));
            lines.push(String::new());
            lines.push(format!("**Tactical Problem:** {}", rec.tactical_problem));
            lines.push(String::new());
            lines.push("### Take Off".into());
            lines.push(String::new());
            for (i, (name, pos, decay)) in rec.take_off.iter().enumerate() {
                lines.push(format!(
                    "{}. {} ({}) -- decay {:.2}",
                    i + 1,
                    name,
                    pos,
                    decay
                ));
            }
            lines.push(String::new());
            lines.push("### Bring On".into());
            lines.push(String::new());
            for (i, c) in rec.bring_on.iter().take(3).enumerate() {
                if i == 0 {
                    lines.push(format!(
                        "1. **{} ({}) -- fit score {:.1}** &larr; BEST MATCH",
                        c.player_name, c.position, c.fit_score
                    ));
                } else if i == 2 {
                    lines.push(format!(
                        "{}. {} ({}) -- fit score {:.1} *(if available)*",
                        i + 1,
                        c.player_name,
                        c.position,
                        c.fit_score
                    ));
                } else {
                    lines.push(format!(
                        "{}. {} ({}) -- fit score {:.1}",
                        i + 1,
                        c.player_name,
                        c.position,
                        c.fit_score
                    ));
                }
            }
        }
    }

    lines.push(String::new());
    lines.push("---".into());
    lines.push(String::new());
    lines.push("*Report generated by SUBS -- StatsBomb match analysis tool*".into());

    std::fs::write(path, lines.join("\n"))?;
    Ok(())
}

// ─── PDF ─────────────────────────────────────────────────────────────────────

pub fn export_pdf(
    path: &Path,
    match_id: &str,
    team: &str,
    minute: u32,
    timestamp: &str,
    scores: &[DecayScore],
    subbed_off: &HashSet<String>,
    recommendation: Option<&Recommendation>,
) -> Result<()> {
    let (doc, page1, layer1) = PdfDocument::new(
        &format!("SUBS Report - {} min {}", team, minute),
        Mm(PAGE_W),
        Mm(PAGE_H),
        "Layer 1",
    );

    let font_bold = doc.add_builtin_font(BuiltinFont::HelveticaBold)?;
    let font_reg = doc.add_builtin_font(BuiltinFont::Helvetica)?;
    let font_mono = doc.add_builtin_font(BuiltinFont::Courier)?;
    let font_mono_bold = doc.add_builtin_font(BuiltinFont::CourierBold)?;

    let mut layer = doc.get_page(page1).get_layer(layer1);
    let mut y = START_Y;
    let mut page_num = 1u32;

    // Inline helpers as closures don't play well with mutable captures; use a
    // helper function instead and pass everything explicitly.
    macro_rules! check {
        ($needed:expr) => {
            if y < BOTTOM_MARGIN + $needed {
                let (nl, ny) = new_page(&doc, &mut page_num);
                layer = nl;
                y = ny;
            }
        };
    }

    macro_rules! put {
        ($text:expr, $size:expr, $font:expr) => {
            layer.use_text($text, $size, Mm(LEFT), Mm(y), $font);
        };
    }

    // Title
    check!(10.0);
    put!("SUBS Analysis Report", 18.0, &font_bold);
    y -= 10.0;

    // Meta
    check!(6.0);
    put!(
        format!("Match: {}   Team: {}   Minute: {}", match_id, team, minute),
        10.0,
        &font_reg
    );
    y -= 5.5;

    check!(5.0);
    put!(format!("Generated: {}", timestamp), 9.0, &font_reg);
    y -= 8.0;

    // Separator
    check!(4.0);
    put!("-".repeat(90), 8.0, &font_mono);
    y -= 7.5;

    // ── Decay table ──────────────────────────────────────────────────────────

    check!(7.0);
    put!("DECAY TABLE", 13.0, &font_bold);
    y -= 6.5;

    check!(9.0);
    put!(
        format!(
            "{:<24}  {:<5}  {:>12}  {:>10}  {:>5}",
            "PLAYER", "POS", "BASELINE APM", "RECENT APM", "DECAY"
        ),
        8.5,
        &font_mono_bold
    );
    y -= 1.5;
    put!("-".repeat(65), 8.5, &font_mono);
    y -= 4.5;

    let mut any_subbed = false;
    for s in scores {
        check!(4.5);
        let is_sub = subbed_off.contains(&s.player_name);
        if is_sub {
            any_subbed = true;
        }

        let name_base: String = if s.player_name.chars().count() > 22 {
            let cut: String = s.player_name.chars().take(21).collect();
            format!("{}~", cut)
        } else {
            s.player_name.clone()
        };
        let display = if is_sub {
            format!("{} *", name_base)
        } else {
            name_base
        };

        put!(
            format!(
                "{:<24}  {:<5}  {:>12.2}  {:>10.2}  {:>5.2}",
                display, s.position, s.baseline_apm, s.recent_apm, s.score
            ),
            8.5,
            &font_mono
        );
        y -= 4.5;
    }

    if any_subbed {
        check!(4.5);
        put!("* = already substituted off", 8.0, &font_reg);
        y -= 4.5;
    }

    // ── Recommendation ───────────────────────────────────────────────────────

    y -= 3.0;
    check!(4.0);
    put!("-".repeat(90), 8.0, &font_mono);
    y -= 8.0;

    match recommendation {
        None => {
            check!(12.0);
            put!(
                format!("No Substitution Recommended at Minute {}", minute),
                13.0,
                &font_bold
            );
            y -= 6.0;
            put!(
                "All players are performing at or near baseline levels.",
                10.0,
                &font_reg
            );
            y -= 5.0;
        }
        Some(rec) => {
            check!(7.0);
            put!(
                format!("SUBSTITUTION RECOMMENDATION -- MINUTE {}", minute),
                13.0,
                &font_bold
            );
            y -= 7.0;

            check!(6.0);
            put!(
                format!("Tactical Problem: {}", rec.tactical_problem),
                11.0,
                &font_bold
            );
            y -= 8.0;

            check!(6.0);
            put!("TAKE OFF:", 11.0, &font_bold);
            y -= 5.5;

            for (i, (name, pos, decay)) in rec.take_off.iter().enumerate() {
                check!(5.0);
                put!(
                    format!("  {}. {} ({}) -- decay {:.2}", i + 1, name, pos, decay),
                    10.0,
                    &font_reg
                );
                y -= 5.0;
            }

            y -= 2.0;
            check!(6.0);
            put!("BRING ON:", 11.0, &font_bold);
            y -= 5.5;

            for (i, c) in rec.bring_on.iter().take(3).enumerate() {
                check!(5.0);
                let suffix = if i == 0 {
                    "  [BEST MATCH]"
                } else if i == 2 {
                    "  (if available)"
                } else {
                    ""
                };
                let fnt = if i == 0 { &font_bold } else { &font_reg };
                put!(
                    format!(
                        "  {}. {} ({}) -- fit score {:.1}{}",
                        i + 1,
                        c.player_name,
                        c.position,
                        c.fit_score,
                        suffix
                    ),
                    10.0,
                    fnt
                );
                y -= 5.0;
            }
        }
    }

    // Footer
    y -= 5.0;
    check!(8.0);
    put!("-".repeat(90), 8.0, &font_mono);
    y -= 5.0;
    put!(
        "Report generated by SUBS -- StatsBomb match analysis tool",
        8.0,
        &font_reg
    );

    // Save
    let bytes = doc.save_to_bytes()?;
    std::fs::write(path, bytes)?;

    Ok(())
}
